[package]
name = "pi-panel"
version = "0.1.0"
authors = ["KK <kk-pub@outlook.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
systemstat = "0.1.5"
serde = { version = "1.0" , features = ["derive"] }
serde_json = "1.0"
actix-files = "0.1.6"
structopt = "0.3.3"
lazy_static="1.4.0"